---

- name: zookeeper directory
  file: name=/var/lib/zookeeper state=directory

- name: master services upstart files
  template: src="{{ item }}.upstart.j2" dest="/etc/init/{{ item }}.conf"
  with_items:
    - zookeeper
  when: ansible_os_family == "Debian"

- name: master services systemd files
  template: src={{ item }}.service.j2 dest=/etc/systemd/system/{{ item }}.service
  with_items:
    - zookeeper
  when: ansible_os_family == "RedHat"

- name: reload systemd
  command: systemctl --system daemon-reload
  when: ansible_os_family == "RedHat"

- name: Pull zookeeper image
  command: docker pull "{{ item }}"
  with_items:
    - "mesoscloud/{{ zookeeper_docker_image }}"

- name: Run zookeeper
  service: name="{{ item }}" enabled=yes state=started
  with_items:
    - zookeeper
