---

dependencies:
  - { role: common, when: dependencies == 'yes' }
  - { role: docker, when: dependencies == 'yes' }
  - { role: zookeeper, when: (inventory_hostname in groups.masters) and (dependencies == 'yes') }
