---

- name: Make sure necessary packages are installed
  become: yes
  action: "{{ ansible_pkg_mgr }}"
  args:
    name: "{{ package }}"
    state: latest
    update_cache: yes
  with_items:
    - python-devel
    - python-netaddr
    - python-markupsafe
    - epel-release
    - vim-enhanced
  loop_control:
    loop_var: package
  run_once: true
  retries: 3
  delay: 5
  register: result
  until: result|success

- name: Make sure necessary packages are installed (all hosts)
  become: yes
  action: "{{ ansible_pkg_mgr }}"
  args:
    name: "{{ package }}"
    state: latest
    update_cache: yes
  with_items:
    - epel-release
    - vim-enhanced
    - git
    - python-devel
    - libxml2-devel
    - libxslt-devel
    - gcc
    - gcc-c++
    - openssl
    - openssl-devel
    - openssl-static
    - libcurl-devel
    - automake
    - autoconf
    - libtool
    - unzip
    - bzip2
  loop_control:
    loop_var: package
